import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;1,400&family=Manrope:wght@400;700&family=Marcellus&display=swap"
          rel="stylesheet"
        />
        <title>My Costa Rica Home</title>
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  )
}
